### ISSUE TITLE
Cannot use import statement outside a module  

### ISSUE THREAD

**Issue by fluffyloopy** [Tenpi/waifu2x#1]
node test.js spits out this 

import waifu2x from "waifu2x"
^^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:877:16)
    at Module._compile (internal/modules/cjs/loader.js:928:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11

**Comment by Moebytes** [comment]
Sorry for the late reply, but make sure you add the following line in your package.json to enable ES Modules: `"type": "module"`
You can also import it using the require syntax as well. `const waifu2x = require("waifu2x").default`

Hope that helps.
