### ISSUE TITLE
fluent-ffmpeg and Waifu2x.parseFramerate can't use the same ffmpeg path

### ISSUE THREAD

**Issue by Specy** [Tenpi/waifu2x#7]
fluent-ffmpeg expects the path of ffmpeg including the ffmpeg.exe at the end, example:
```
C:\Users\dione\Desktop\Progetti\electron\scapix\ffmpeg\ffmpeg.exe
```
and instead the Waifu2x.parseFramerate function expects the path to be
```
C:\Users\dione\Desktop\Progetti\electron\scapix\ffmpeg\
```
as it needs to `cd` to that path.

When i do:
```js
let videoOptions = {
     quality:0,
     noise: noise,
     scale: el.scale,
     ffmpegPath: "C:\Users\dione\Desktop\Progetti\electron\scapix\ffmpeg\ffmpeg.exe"
}
Waifu2x.upscaleVideo(filePath,endPath,videoOptions)
```
i get the error: 
```
TypeError: Cannot read property '0' of null
[1]     at C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:423:78
[1]     at step (C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:33:23)
[1]     at Object.next (C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:14:53)
[1]     at fulfilled (C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:5:58)
```
Which produces the stderr "path name not valid"
While if i remove `ffmpeg.exe` from ffmpegPath i get this error:
```
 Error: spawn C:\Users\dione\Desktop\Progetti\electron\scapix\ffmpeg ENOENT
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
[1]     at onErrorNT (internal/child_process.js:469:16)
[1]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[1]   errno: 'ENOENT',
[1]   code: 'ENOENT',
[1]   syscall: 'spawn C:\\Users\\dione\\Desktop\\Progetti\\electron\\scapix\\ffmpeg',
[1]   path: 'C:\\Users\\dione\\Desktop\\Progetti\\electron\\scapix\\ffmpeg',
[1]   spawnargs: [ '-formats' ]
[1] }
```
coming from fluent-ffmpeg

Fix would be to just remove "ffmpeg.exe" from [ffmpegPath](https://github.com/Tenpi/waifu2x/blob/ec1416a6db514def9d73e4d0442cd4dd2352e32b/waifu2x.ts#L305)

**Comment by Moebytes** [comment]
You were using `cd ${ffmpegPath}` in the code you provided before, so I thought it was a directory! You can upgrade to `v0.3.8`.
